#!/bin/sh

. ${SCRIPTSDIR}/mtwInclude.sh

VER=0.0.1

usage () {
cat << EOF

${0} v${VER}
Usage: ${0} [directory]
License: GPL

EOF
}

if [ ${#} -lt "1" ]; then
    usage
    exit 0
fi    

if [ -d ${1} ]; then
	tar cfh ${1}-${HOST}-${PACKDATE}.tar --exclude='.svn' ${1}
	bzip2 ${1}-${HOST}-${PACKDATE}.tar
fi

