#!/bin/sh

cd $1
echo $PWD
for i in *; do
	echo "$PWD/$i"
	if [ -d "$PWD/$i" ]; then
		#echo "."
		cd $i
		#echo "${PWD}/.svn"
		if [ -d "${PWD}/.svn" ]; then    
			echo "Updating $i"
			svn update
		fi
		cd ..
	fi
done


